### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by wilecoyote1** [Tobi-De/falco#98]
on windows 11, in powershell 7.44

when i execute the command

falco start-project myjourney && cd myjourney

i've got the message

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\falco.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python\Python310\lib\site-packages\falco\__main__.py", line 33, in main
    cappa.invoke(Falco)
  File "C:\Python\Python310\lib\site-packages\cappa\base.py", line 149, in invoke
    with resolved.get(concrete_output) as value:
  File "C:\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Python\Python310\lib\site-packages\cappa\invoke.py", line 65, in get
    result = callable(**finalized_kwargs)
  File "C:\Python\Python310\lib\site-packages\falco\commands\start_project.py", line 109, in __call__
    falco_config = read_falco_config(pyproject_path)
  File "C:\Python\Python310\lib\site-packages\falco\config.py", line 52, in read_falco_config
    pyproject = tomlkit.parse(pyproject_path.read_text())
  File "C:\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5998: character maps to <undefined>

**Comment by Tobi-De** [comment]
Hi @wilecoyote1 
I don't use windows so I can't really try to see if my changes fix the issue but I've just made a new release, try it to see if it fixes your issue

```shell
pip install "falco-cli[just]"==0.23.1
```

**Comment by wilecoyote1** [comment]
the command 

pip install "falco-cli[just]"==0.23.1  

return 

ERROR: Invalid requirement: '==0.23.1': Expected package name at the start of dependency specifier
    ==0.23.1
    ^

i try 
 pip install -U falco-cli 
 and i update to .0.23.1
 
 when i try 
 
  falco start-project myjourney && cd myjourney 
  
  at the end, "building formatter"
  
  i'v got
  
  Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\falco.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python310\lib\site-packages\falco\__main__.py", line 33, in main
    cappa.invoke(Falco)
  File "C:\Python310\lib\site-packages\cappa\base.py", line 149, in invoke
    with resolved.get(concrete_output) as value:
  File "C:\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Python310\lib\site-packages\cappa\invoke.py", line 65, in get
    result = callable(**finalized_kwargs)
  File "C:\Python310\lib\site-packages\falco\commands\start_project.py", line 126, in __call__
    write_falco_config(pyproject_path=pyproject_path, **config)
  File "C:\Python310\lib\site-packages\falco\config.py", line 38, in write_falco_config
    pyproject = tomlkit.parse(pyproject_path.read_text())
  File "C:\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6007: character maps to <undefined>

**Comment by Tobi-De** [comment]
@wilecoyote1 try `pip install falco-cli==0.23.1`

**Comment by wilecoyote1** [comment]
yes, i have already the latest version

Requirement already satisfied: falco-cli==0.23.1 in c:\python310\lib\site-packages (0.23.1)

when i launch the command 

falco start-project myjourney && cd myjourney

i've got download htmx...

and still the same trace

**Comment by Tobi-De** [comment]
> and still the same trace
can you paste it, it's probably the same error, but trying to see if it fails exactly at the same point

**Comment by wilecoyote1** [comment]
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python310\Scripts\falco.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python310\lib\site-packages\falco\__main__.py", line 33, in main
    cappa.invoke(Falco)
  File "C:\Python310\lib\site-packages\cappa\base.py", line 149, in invoke
    with resolved.get(concrete_output) as value:
  File "C:\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Python310\lib\site-packages\cappa\invoke.py", line 65, in get
    result = callable(**finalized_kwargs)
  File "C:\Python310\lib\site-packages\falco\commands\start_project.py", line 126, in __call__
    write_falco_config(pyproject_path=pyproject_path, **config)
  File "C:\Python310\lib\site-packages\falco\config.py", line 38, in write_falco_config
    pyproject = tomlkit.parse(pyproject_path.read_text())
  File "C:\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 6007: character maps to <undefined>

**Comment by Tobi-De** [comment]
@wilecoyote1 The new version is `v0.23.2`, try again, might take a few minutes to be available

**Comment by wilecoyote1** [comment]
ok, i upgrade to the new version and got this trace

Traceback (most recent call last):
  File "C:\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Python\Python310\Scripts\falco.exe\__main__.py", line 7, in <module>
    sys.exit(main())
  File "C:\Python\Python310\lib\site-packages\falco\__main__.py", line 33, in main
    cappa.invoke(Falco)
  File "C:\Python\Python310\lib\site-packages\cappa\base.py", line 149, in invoke
    with resolved.get(concrete_output) as value:
  File "C:\Python\Python310\lib\contextlib.py", line 135, in __enter__
    return next(self.gen)
  File "C:\Python\Python310\lib\site-packages\cappa\invoke.py", line 65, in get
    result = callable(**finalized_kwargs)
  File "C:\Python\Python310\lib\site-packages\falco\commands\start_project.py", line 126, in __call__
    write_falco_config(pyproject_path=pyproject_path, **config)
  File "C:\Python\Python310\lib\site-packages\falco\config.py", line 38, in write_falco_config
    pyproject = tomlkit.parse(pyproject_path.read_text()) if pyproject_path.exists() else {}
  File "C:\Python\Python310\lib\pathlib.py", line 1135, in read_text
    return f.read()
  File "C:\Python\Python310\lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x90 in position 5998: character maps to <undefined>

**Comment by Tobi-De** [comment]
Just to make sure, the directory for the project you are trying to create does not exists right ?

**Comment by wilecoyote1** [comment]
Yes
I remove the directory every Time otherwise the script can’t run

**Comment by Tobi-De** [comment]
Ok this is really weird, new version `v0.23.3`

**Comment by wilecoyote1** [comment]
it works ! 

bravo

thanks for all

**Comment by Tobi-De** [comment]
> it works ! 
> 
> bravo
> 
> thanks for all

Great, thanks to you, for reporting and keeping up with the issue :) 
I did not test the project on windows, so there might be more issues, if it happens please report them
